<?php

require_once __DIR__ . '/../src/core/init.php';

$GLOBALS['dynamicMeta'] = [];

require_once __DIR__ . '/../src/core/lang/en.php';
require_once __DIR__ . '/../src/core/lang/el.php';

// Get the 'page' parameter
$pageParam = isset($_GET['page']) ? $_GET['page'] : '';

// Treat the root URL as "home" / Default Page
if (empty($pageParam)) {
    $pageSegments = ['home'];
} else {
    $pageSegments = explode('/', trim($pageParam, '/'));
}

$pageManager = new PageController();

// Attempt to retrieve page info and count of segments used
$pageResult = $pageManager->getPageInfo($pageSegments);

if (!$pageResult) {
    http_response_code(404);
    require_once __DIR__ . '/../src/includes/front/header.php';
    echo '<body>';
    echo '<div class="container">';
    require_once __DIR__ . "/../src/templates/404.php";
    die();
}

$pageInfo = $pageResult['pageInfo'];
$segmentsUsed = $pageResult['segmentsUsed'];

// Extract parameters from the URL
$params = array_slice($pageSegments, $segmentsUsed);

$params = array_map('rawurldecode', $params);


$pagesList = $pageManager->getAllPages();
$dbConnection = Database::getInstance();

if ($pageInfo['reqLogin']) {
    if (!$mainUser->isLoggedIn()) {
        header("Location: /login");
        die();
    }

    if ($mainUser->isLoggedIn() && !$mainUser->hasPermission($pageInfo['allowTo'])) {
        // echo "You dont have permission to access this page";
        require_once __DIR__ . "/../src/templates/dennied.php";
        die();
    }
    
}

//Load Front-end Files
if ($pageInfo['frontEnd']) {
    // Start output buffering
    ob_start();

    // Include the template (e.g., template.php)
    require_once __DIR__ . "/../src/templates/front/{$pageInfo['template']}";

    // Get the content generated by the template
    $templateContent = ob_get_clean();

    // Include header after $GLOBALS['dynamicMeta'] is set in the template
    require_once __DIR__ . '/../src/includes/front/header.php';
    
    //Preloader
    echo '<div id="preloader"><div id="status" class="">&nbsp;</div></div>';
    
    echo '<body><div class="bg-gr"></div>';
   
    if ($pageInfo['showNavbar']) {
        require_once __DIR__ . '/../src/templates/menus/front/main_menu.php';
    }

    // Output the content from the template
    echo $templateContent;

    require_once __DIR__ . '/../src/includes/front/footer.php';
}
else if ($pageInfo['backEnd']) { //Load Back-end Files

    require_once __DIR__ . '/../src/includes/back/header.php';
    echo '<body>';

    echo '<main role="main" id="main" class="c-main">';
	echo '<div class="content-wrapper content-wrapper--with-bg">';
    if ($pageInfo['showNavbar']) {
        require_once __DIR__ . '/../src/templates/menus/back/main_menu.php';
    }

    try {

        if (!file_exists(__DIR__ . "/../src/templates/back/{$pageInfo['template']}"))
        throw new Exception($pageInfo['template'] . " does not exist");
        else
            require_once __DIR__ . "/../src/templates/back/{$pageInfo['template']}";

    } catch (Exception $e) {
        echo "Message : " . $e->getMessage();
    }


    echo '</main>';
    echo '</div>';
    require_once __DIR__ . '/../src/includes/back/footer.php';
} else { //Load 404 Page
    http_response_code(404);
    require_once __DIR__ . '/../src/includes/front/header.php';
    echo '<body>';
    echo '<div class="container">';
    require_once __DIR__ . "/../src/templates/404.php";
}
